"""NINJA Social Intelligence Foundation, Part II §27-29: the ONE canonical CommandRegistry.
Invariant (spec §29): HELP CANNOT DRIFT FROM REAL COMMANDS - bot/handlers/business_context.py's
own `@router.message(Command(...))` decorators are generated by iterating this SAME registry
(see that module's own `_register_all()`), never a second, hand-maintained list. `/help` and
`/help <command>` both render directly from `CommandDefinition.examples`/`.detailed_help` -
never a separately-authored help string that could drift out of sync."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CommandDefinition:
    name: str
    description: str
    examples: tuple[str, ...] = ()
    detailed_help: str = ""
    enabled: bool = True
    # Commands with is_mutation=True go through parse -> proposal -> confirm; a pure read command
    # (/status, /help) never creates a BusinessContextProposal at all.
    is_mutation: bool = True


COMMAND_REGISTRY: dict[str, CommandDefinition] = {
    "product": CommandDefinition(
        name="product", description="Информация о продукте.",
        examples=(
            "/product\n\nNINJA Store находится в разработке.\nНа старте продаём в основном "
            "технику Apple.\nЗапуск хотим сделать в ноябре.",
        ),
        detailed_help=(
            "Назначение: создать или изменить постоянный контекст продукта (статус, описание, "
            "фичи, цена, ссылки).\n\n"
            "Можно писать обычным языком - AI разберёт сообщение и покажет структурированную "
            "версию перед сохранением."
        ),
    ),
    "campaign": CommandDefinition(
        name="campaign", description="Запуск или маркетинговая кампания.",
        examples=(
            "/campaign\n\nNINJA AI запускаем 5 октября.\nДо 20 сентября прямой рекламы не делаем.\n"
            "После 20-го начинаем тизеры.",
        ),
        detailed_help=(
            "Назначение: создать или изменить маркетинговую кампанию/запуск продукта - дату, "
            "статус (предварительно/подтверждено/перенесено), ключевые сообщения, ограничения.\n\n"
            "Дата и статус - разные вещи: TENTATIVE-дата не значит, что её можно называть публично."
        ),
    ),
    "milestone": CommandDefinition(
        name="milestone", description="Важное событие внутри разработки.",
        examples=(
            "/milestone\n\nNINJA AI Design Mode прошёл внутреннюю приёмку.\nПублично пока не "
            "анонсируем.\nМатериалы можно готовить.",
        ),
        detailed_help=(
            "Назначение: зафиксировать важное внутреннее событие (приёмка, готовность фичи, "
            "партнёрство). Важно: milestone - это контекст, а не команда \"сделать пост\"."
        ),
    ),
    "directive": CommandDefinition(
        name="directive", description="Стратегическая команда директорам.",
        examples=(
            "/directive\n\nСледующие две недели увеличиваем долю AI-контента.\nStore пока не "
            "продвигаем.\nVPN остаётся основной точкой конверсии.",
        ),
        detailed_help=(
            "Назначение: явное указание от основателя/руководителя, которое директора платформ "
            "не могут переопределить оптимизацией. По умолчанию доступно только роли FOUNDER."
        ),
    ),
    "claim": CommandDefinition(
        name="claim", description="Что разрешено и запрещено говорить публично.",
        examples=(
            "/claim\n\nNINJA AI.\n\nМожно: говорить про Chat / Design / Code.\nНельзя: раскрывать "
            "цену; называть точное количество моделей.",
        ),
        detailed_help=(
            "Назначение: явно разграничить APPROVED / RESTRICTED / EMBARGOED публичные "
            "утверждения о продукте. Факт, известный внутри команды, не становится автоматически "
            "разрешённым для публикации."
        ),
    ),
    "context": CommandDefinition(
        name="context", description="Универсальное обновление бизнес-контекста.",
        examples=(
            "/context\n\nРелиз AI переносится примерно на неделю.\nНовой точной даты пока нет.\n"
            "Countdown остановить. Общий прогрев продолжить.",
        ),
        detailed_help=(
            "Назначение: одно сообщение может одновременно изменить продукт, кампанию, milestone "
            "и directive. Вы увидите ВСЕ предложенные изменения перед подтверждением - ни одно "
            "сообщение не становится активным контекстом без вашего подтверждения."
        ),
    ),
    "status": CommandDefinition(
        name="status", description="Текущее состояние продуктов и кампаний.", is_mutation=False,
        examples=("/status", "/status AI"),
        detailed_help="Показывает текущий подтверждённый Business Context. Ничего не изменяет.",
    ),
    "help": CommandDefinition(
        name="help", description="Инструкция по командам.", is_mutation=False,
        examples=("/help", "/help campaign"),
        detailed_help="Показывает список доступных вам команд, или подробную справку по одной команде.",
    ),
}


def commands_for_role(allowed_command_names: frozenset[str]) -> list[CommandDefinition]:
    return [c for name, c in COMMAND_REGISTRY.items() if c.enabled and name in allowed_command_names]


def get_command(name: str) -> CommandDefinition | None:
    return COMMAND_REGISTRY.get(name)
