"""NINJA Social Intelligence Foundation, Part II §27-29: the ONE canonical CommandRegistry.
Invariant (spec §29): HELP CANNOT DRIFT FROM REAL COMMANDS - bot/handlers/business_context.py's
own `@router.message(Command(...))` decorators are generated by iterating this SAME registry
(see that module's own `_register_all()`), never a second, hand-maintained list. `/help` and
`/help <command>` both render directly from `CommandDefinition.examples`/`.detailed_help` -
never a separately-authored help string that could drift out of sync."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CommandDefinition:
    name: str
    description: str
    examples: tuple[str, ...] = ()
    detailed_help: str = ""
    enabled: bool = True
    # Commands with is_mutation=True go through parse -> proposal -> confirm; a pure read command
    # (/status, /help) never creates a BusinessContextProposal at all.
    is_mutation: bool = True


COMMAND_REGISTRY: dict[str, CommandDefinition] = {
    "product": CommandDefinition(
        name="product", description="Информация о продукте.",
        examples=(
            "/product\n\nNINJA Store находится в разработке.\nНа старте продаём в основном "
            "технику Apple.\nЗапуск хотим сделать в ноябре.",
        ),
        detailed_help=(
            "Назначение: создать или изменить постоянный контекст продукта (статус, описание, "
            "фичи, цена, ссылки).\n\n"
            "Можно писать обычным языком - AI разберёт сообщение и покажет структурированную "
            "версию перед сохранением."
        ),
    ),
    "campaign": CommandDefinition(
        name="campaign", description="Запуск или маркетинговая кампания.",
        examples=(
            "/campaign\n\nNINJA AI запускаем 5 октября.\nДо 20 сентября прямой рекламы не делаем.\n"
            "После 20-го начинаем тизеры.",
        ),
        detailed_help=(
            "Назначение: создать или изменить маркетинговую кампанию/запуск продукта - дату, "
            "статус (предварительно/подтверждено/перенесено), ключевые сообщения, ограничения.\n\n"
            "Дата и статус - разные вещи: TENTATIVE-дата не значит, что её можно называть публично."
        ),
    ),
    "milestone": CommandDefinition(
        name="milestone", description="Важное событие внутри разработки.",
        examples=(
            "/milestone\n\nNINJA AI Design Mode прошёл внутреннюю приёмку.\nПублично пока не "
            "анонсируем.\nМатериалы можно готовить.",
        ),
        detailed_help=(
            "Назначение: зафиксировать важное внутреннее событие (приёмка, готовность фичи, "
            "партнёрство). Важно: milestone - это контекст, а не команда \"сделать пост\"."
        ),
    ),
    "directive": CommandDefinition(
        name="directive", description="Стратегическая команда директорам.",
        examples=(
            "/directive\n\nСледующие две недели увеличиваем долю AI-контента.\nStore пока не "
            "продвигаем.\nVPN остаётся основной точкой конверсии.",
        ),
        detailed_help=(
            "Назначение: явное указание от основателя/руководителя, которое директора платформ "
            "не могут переопределить оптимизацией. По умолчанию доступно только роли FOUNDER."
        ),
    ),
    "claim": CommandDefinition(
        name="claim", description="Что разрешено и запрещено говорить публично.",
        examples=(
            "/claim\n\nNINJA AI.\n\nМожно: говорить про Chat / Design / Code.\nНельзя: раскрывать "
            "цену; называть точное количество моделей.",
        ),
        detailed_help=(
            "Назначение: явно разграничить APPROVED / RESTRICTED / EMBARGOED публичные "
            "утверждения о продукте. Факт, известный внутри команды, не становится автоматически "
            "разрешённым для публикации."
        ),
    ),
    "context": CommandDefinition(
        name="context", description="Универсальное обновление бизнес-контекста.",
        examples=(
            "/context\n\nРелиз AI переносится примерно на неделю.\nНовой точной даты пока нет.\n"
            "Countdown остановить. Общий прогрев продолжить.",
        ),
        detailed_help=(
            "Назначение: одно сообщение может одновременно изменить продукт, кампанию, milestone "
            "и directive. Вы увидите ВСЕ предложенные изменения перед подтверждением - ни одно "
            "сообщение не становится активным контекстом без вашего подтверждения."
        ),
    ),
    "status": CommandDefinition(
        name="status", description="Текущее состояние продуктов и кампаний.", is_mutation=False,
        examples=("/status", "/status AI"),
        detailed_help="Показывает текущий подтверждённый Business Context. Ничего не изменяет.",
    ),
    "help": CommandDefinition(
        name="help", description="Инструкция по командам.", is_mutation=False,
        examples=("/help", "/help campaign"),
        detailed_help="Показывает список доступных вам команд, или подробную справку по одной команде.",
    ),
    # SOCIAL-INTELLIGENCE-INTEGRATION-1 §6-12/§21/§24: Director Console - all read-only, no
    # confirmation flow, no proposal (is_mutation=False, mirroring /status). Filters
    # ("/plan telegram") only trim which platform's section is shown - never a separate DSL.
    "directors": CommandDefinition(
        name="directors", description="Состояние AI-директоров (что реально работает).", is_mutation=False,
        examples=("/directors",),
        detailed_help=(
            "Показывает реальное состояние директоров бизнеса, Telegram и Instagram - на основе "
            "фактических feature-флагов, накопленных данных и реализованных сервисов. Никогда не "
            "показывает ACTIVE, если реального включённого воздействия на продакшн нет."
        ),
    ),
    "plan": CommandDefinition(
        name="plan", description="Текущий кросс-платформенный контент-план.", is_mutation=False,
        examples=("/plan", "/plan telegram", "/plan instagram"),
        detailed_help=(
            "Показывает бизнес-приоритет, фазу кампании, действующие директивы основателя, и "
            "отдельные (не идентичные) планы для Telegram и Instagram."
        ),
    ),
    "opportunities": CommandDefinition(
        name="opportunities", description="Актуальные возможности для контента.", is_mutation=False,
        examples=("/opportunities", "/opportunities telegram", "/opportunities instagram"),
        detailed_help=(
            "Показывает объединённый список NEWS/PRODUCT/TREND-возможностей с их измерениями "
            "(новостная ценность, релевантность кампании, релевантность тренда) - без единой "
            "\"магической\" оценки."
        ),
    ),
    "calendar": CommandDefinition(
        name="calendar", description="Будущий запланированный контент и его статус.", is_mutation=False,
        examples=("/calendar", "/calendar instagram"),
        detailed_help=(
            "Показывает запланированный контент (сейчас - только Instagram, у Telegram ещё нет "
            "персистентного календаря) со статусами ACTIVE/STALE/INVALIDATED/RESCHEDULED/DONE/"
            "CANCELLED."
        ),
    ),
    "performance": CommandDefinition(
        name="performance", description="Реальные сигналы эффективности (не тщеславные метрики).", is_mutation=False,
        examples=("/performance", "/performance telegram", "/performance instagram"),
        detailed_help=(
            "Показывает только подтверждённые данными сигналы - никогда не показывает метрики "
            "внутреннего редакционного чата как метрики публичной аудитории, и никогда не "
            "показывает 0 вместо \"данные недоступны\"."
        ),
    ),
    # SOCIAL-INTELLIGENCE-OPS-1 §3/§4/§7: /surface - reading status is broadly available (see
    # services/business_context_roles.py); SUBMITTING a configuration change additionally requires
    # FOUNDER tier, enforced inside bot/handlers/telegram_surface.py itself (spec §5) - the
    # registry/role system only gates "may use /surface at all".
    "surface": CommandDefinition(
        name="surface", description="Настройка и статус поверхностей Telegram (публичные/внутренние).",
        examples=(
            "/surface",
            "/surface\n\nNINJA PULSE — публичный новостной канал.\nUsername: @ninjapulse.\n"
            "Использовать его как PUBLIC_NEWS_CHANNEL.\nАналитику включить.",
        ),
        detailed_help=(
            "Без текста - показывает текущий статус всех настроенных поверхностей (публичные "
            "каналы vs внутренний редакторский чат). С текстом - предлагает настройку новой "
            "поверхности (доступно только FOUNDER): AI разберёт сообщение, покажет предложенную "
            "структуру, и применит её только после подтверждения. Внутренний редакторский чат "
            "никогда не становится источником данных об аудитории без явного подтверждения роли "
            "PUBLIC_* с включённой аналитикой."
        ),
    ),
    # VISUAL-DESIGN-AUTONOMY-1 §51/§52: /design read is available to every role with director
    # console access; freeze/unfreeze/rollback additionally require FOUNDER, enforced inside
    # bot/handlers/visual_design.py itself (same "directive"-allowed proxy pattern as /surface).
    "design": CommandDefinition(
        name="design", description="Статус автономной визуальной системы (бриф, здоровье, бюджет).",
        examples=("/design", "/design news", "/design freeze data"),
        detailed_help=(
            "Без аргумента - статус всех scope: версия действующего Designer Brief, здоровье "
            "(HEALTHY/WATCH/DEGRADED/FROZEN/INSUFFICIENT_DATA), дневной бюджет. С именем scope - "
            "подробности по нему, включая статус адаптации (Stable/Possible signal/Repeated "
            "pattern detected/Candidate ready/Candidate rejected/Frozen). FOUNDER дополнительно "
            "может: /design freeze <scope>, /design unfreeze <scope>, /design rollback <scope>, "
            "/design reconsider <scope> - каждое требует подтверждения; reconsider запускает тот "
            "же ограниченный генератор пересмотра брифа (только при наличии REPEATED_PATTERN "
            "evidence - никогда произвольный текст). Открытие /design никогда не запускает "
            "генерацию дизайна и не вызывает AI Gateway."
        ),
    ),
    # SOCIAL-INTELLIGENCE-PRELAUNCH-1 §12/§13/§14: /launch - reading launch context is broadly
    # available (see services/business_context_roles.py); SUBMITTING an instruction additionally
    # requires FOUNDER tier, enforced inside bot/handlers/launch.py itself (spec §12) - the
    # registry/role system only gates "may use /launch at all". Gated overall by
    # settings.social_launch_context_enabled (default False).
    "launch": CommandDefinition(
        name="launch", description="Стратегия запуска/перехода Telegram и Instagram до появления первых данных.",
        examples=(
            "/launch",
            "/launch telegram Текущий канал - NINJA VPN, готовим переход в NINJA PULSE. Старые "
            "посты VPN - только контекст, не данные для обучения.",
            "/launch instagram Аккаунт NINJA PULSE пустой, начинаем с нуля.",
        ),
        detailed_help=(
            "Без текста - показывает текущий launch context для Telegram и Instagram (режим, "
            "целевая идентичность, дата запуска, политика обучения и старого контента). С "
            "текстом (доступно только FOUNDER) - предлагает обновление launch context для "
            "указанной платформы: AI разберёт сообщение, покажет предложенную структуру, и "
            "применит её только после подтверждения. История версий сохраняется полностью - "
            "ничего не удаляется."
        ),
    ),
}


def commands_for_role(allowed_command_names: frozenset[str]) -> list[CommandDefinition]:
    return [c for name, c in COMMAND_REGISTRY.items() if c.enabled and name in allowed_command_names]


def get_command(name: str) -> CommandDefinition | None:
    return COMMAND_REGISTRY.get(name)
