"""Versioned Safe Glossary - Phase 17 M4 (docs/phase17_m4_beginner_friendly_copywriting_report.md).

A small, deterministic, hand-curated, hand-reviewed glossary of terms that actually appeared in
this project's own real corpus across Phase 17 M0-M3's audits (never a general-purpose knowledge
base, never generated by an LLM, never expanded automatically). Every definition is neutral and
factual - no marketing language ("leading", "popular", "powerful") and no claim that isn't a
stable, durable fact about what the term *means*, never about any specific company's standing.

Adding a term here is a deliberate, reviewed code change - `services/beginner_friendly.py` never
falls back to inventing a definition for a term this glossary doesn't contain (M4's own explicit
"if the term is absent from the glossary and the source does not explain it, do not invent an
explanation" rule); an absent term is either left unexplained or the sentence around it is
simplified, never silently filled in from model's own world knowledge.
"""
from __future__ import annotations

GLOSSARY_VERSION = "v1"

# term (lowercase, matched via classify_terms_to_explain()'s own normalization) -> a short,
# neutral, factual definition safe to use as an inline appositive explanation.
GLOSSARY: dict[str, str] = {
    "llm": "большая языковая модель — тип ИИ-системы, обученной на больших объёмах текста для "
           "генерации и понимания языка",
    "inference": "инференс — использование уже обученной ИИ-модели для получения результата, "
                 "в отличие от её обучения",
    "fine-tuning": "дообучение — дополнительное обучение уже готовой ИИ-модели на небольшом "
                   "наборе данных для конкретной задачи",
    "open weights": "открытые веса — публикация обученных параметров ИИ-модели, в отличие от "
                    "доступа к ней только через API",
    "benchmark": "бенчмарк — стандартизированный тест для измерения и сравнения "
                 "производительности ИИ-моделей",
    "token": "токен — минимальная единица текста (часть слова или символ), которую обрабатывает "
             "языковая модель",
    "agent": "ИИ-агент — программная система на основе ИИ-модели, способная самостоятельно "
             "планировать и выполнять действия для достижения цели",
    "quantization": "квантование — метод снижения численной точности параметров модели для "
                     "уменьшения её размера и ускорения работы",
    "multimodal": "мультимодальность — способность ИИ-системы обрабатывать более одного типа "
                   "данных одновременно, например текст и изображения",
    "npu": "NPU (Neural Processing Unit) — блок процессора, спроектированный специально для "
           "эффективного выполнения ИИ-вычислений",
    "lithography": "литография — производственный процесс нанесения схем на полупроводниковые "
                    "пластины при изготовлении чипов",
    "gpu": "GPU (Graphics Processing Unit) — чип, изначально созданный для рендеринга графики, "
           "который также широко используется для ИИ-вычислений",
    "antitrust": "антимонопольное регулирование — законы и меры государства, направленные на "
                 "предотвращение недобросовестного ограничения конкуренции",
    "sota": "SOTA (state of the art) — лучший из опубликованных результатов на данный момент "
            "для конкретной задачи или бенчмарка",
    "series a": "раунд Series A — как правило, первый крупный раунд венчурного финансирования "
                "компании после начального посевного этапа",
}


def lookup(term: str) -> str | None:
    """Case-insensitive, exact-term lookup only - never a fuzzy/partial match (a partial match
    could silently attach the wrong definition to a similarly-spelled but different term)."""
    return GLOSSARY.get(term.strip().lower())


def known_terms() -> frozenset[str]:
    return frozenset(GLOSSARY.keys())
