"""NINJA PULSE Visual System v1 - AI Presentation Director + deterministic guards.

Zero new LLM call. The "AI proposal" this module consumes is the EXISTING Copywriting v8-family
output's own `viral_potential`/`meme_potential`/`story_led`/`quote` fields - already generated by
the same paid call every router-mode draft already makes, just never read for presentation intent
before now. This module never calls the LLM Gateway itself.

Strict separation of concerns (spec's own "AI is not a safety gate" rule):
    AI PROPOSES (existing Copywriting fields)
        -> DETERMINISTIC GUARD VALIDATES (this module's own pure functions)
        -> caller (worker/content_cycle.py) hands the decision to the renderer

This module does not decide whether to publish, how important a story is, which facts are true,
which source is trusted, or which media candidate to use - all of that is already decided upstream
(selection, Scoring, Editorial Relevance, Editorial Treatment, media ranking) and is passed in
here, read-only, never re-derived.

BREAKING/DATA/QUOTE all fail closed to NEWS on any grounding failure - see each guard's own
docstring. NEWS is therefore the only type this module can never "fail" to produce.
"""
from __future__ import annotations

import re
import unicodedata
import zlib
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from database.models.news_event import EventCategory
from schemas.topic_taxonomy import ArticleTopic
from services.channel_relevance import classify_article_topic
from services.editorial_treatment import MAJOR

NEWS = "NEWS"
BREAKING = "BREAKING"
DATA = "DATA"
QUOTE = "QUOTE"

CATEGORY_AI = "AI"
CATEGORY_TECH = "TECH"
CATEGORY_GADGETS = "GADGETS"
CATEGORY_SOFTWARE = "SOFTWARE"
CATEGORY_SCIENCE = "SCIENCE"
CATEGORY_SECURITY = "SECURITY"
CATEGORY_SOCIAL = "SOCIAL"
CATEGORY_BUSINESS = "BUSINESS"

CAPTION_ABOVE = "ABOVE"
CAPTION_BELOW = "BELOW"

BRANDING_MINIMAL = "MINIMAL"
BRANDING_EDITORIAL = "EDITORIAL"
BRANDING_STRONG = "STRONG"

_TOPIC_TO_CATEGORY: dict[ArticleTopic, str] = {
    ArticleTopic.AI: CATEGORY_AI,
    ArticleTopic.GADGETS: CATEGORY_GADGETS,
    ArticleTopic.CONSUMER_TECH: CATEGORY_GADGETS,
    ArticleTopic.SOFTWARE: CATEGORY_SOFTWARE,
    ArticleTopic.CHIPS: CATEGORY_TECH,
    ArticleTopic.CYBERSECURITY: CATEGORY_SECURITY,
    ArticleTopic.BUSINESS_TECH: CATEGORY_BUSINESS,
    ArticleTopic.REGULATION_TECH: CATEGORY_BUSINESS,
    ArticleTopic.BIG_TECH: CATEGORY_TECH,
    ArticleTopic.SCIENCE_TECH: CATEGORY_SCIENCE,
    ArticleTopic.GAMING_TECH: CATEGORY_TECH,
    # Non-tech topics - display bucket only. Events this far into presentation have already
    # cleared services/news_editorial_relevance.py's OUT_OF_SCOPE hard-exclusion upstream (a
    # different, gating concern this module never re-checks), so this branch is expected rare.
    ArticleTopic.ENTERTAINMENT: CATEGORY_SOCIAL,
    ArticleTopic.GAMING_CONTENT: CATEGORY_SOCIAL,
    ArticleTopic.POLITICS: CATEGORY_SOCIAL,
    ArticleTopic.SPORTS: CATEGORY_SOCIAL,
    ArticleTopic.LIFESTYLE: CATEGORY_SOCIAL,
    ArticleTopic.CRIME: CATEGORY_SOCIAL,
}

_BRANDING_BY_TREATMENT: dict[str, tuple[str, int]] = {
    "BRIEF": (BRANDING_MINIMAL, 1),
    "STANDARD": (BRANDING_MINIMAL, 2),
    "MAJOR": (BRANDING_EDITORIAL, 3),
}

_BREAKING_MIN_SCORE = 85

_BREAKING_COMPANY_PHRASES: tuple[str, ...] = (
    "openai", "chatgpt", "gpt", "anthropic", "claude", "google", "gemini", "apple", "iphone",
    "microsoft", "meta", "amazon", "nvidia", "github",
)

_BREAKING_SIGNAL_PHRASES: tuple[str, ...] = (
    # outage
    "is down", "outage", "went down", "down worldwide", "global outage", "not working",
    "недоступен", "легла", "лег", "сбой в работе", "глобальный сбой",
    # critical security
    "actively exploited", "critical vulnerability", "zero-day exploited", "critical exploit",
    "критическая уязвимость", "активно эксплуатируется",
    # landmark legal
    "landmark antitrust", "landmark ruling", "forced to divest", "ordered to divest", "breakup",
    "историческое антимонопольное",
    # major launch / acquisition (only counted together with a company match above)
    "unveils", "launches", "releases", "announces", "acquisition", "acquires", "to acquire",
    "выпустила", "представила", "анонсировала", "запустила", "приобрела",
)

_NUMBER_UNIT_RE = re.compile(
    r"(?:\$\s*)?(?P<value>\d[\d,.]*\d|\d)\s*(?P<unit>%|percent|процент\w*|млн\.?|million|млрд\.?|billion|"
    r"тыс\.?|thousand|k\b)",
    re.IGNORECASE,
)


def _compile(phrases: tuple[str, ...]) -> re.Pattern[str]:
    alternation = "|".join(re.escape(phrase) for phrase in sorted(phrases, key=len, reverse=True))
    return re.compile(rf"\b(?:{alternation})\b")


_BREAKING_COMPANY_PATTERN = _compile(_BREAKING_COMPANY_PHRASES)
_BREAKING_SIGNAL_PATTERN = _compile(_BREAKING_SIGNAL_PHRASES)


def _normalize(text: str) -> str:
    return " ".join(unicodedata.normalize("NFKC", text).lower().replace("ё", "е").split())


@dataclass(frozen=True)
class DataCandidate:
    value: str
    unit: str
    label: str
    evidence_fact: str


@dataclass(frozen=True)
class QuoteCandidate:
    text: str
    speaker: str | None


@dataclass(frozen=True)
class PresentationDecision:
    presentation_type: str
    category: str
    caption_position: str
    branding_strength: str
    brand_media: bool
    visual_priority: int
    data_candidate: DataCandidate | None
    quote_candidate: QuoteCandidate | None
    reason: str


def build_editorial_code(identifier: UUID) -> str:
    """Deterministic, display-only "NP-XXXX" code (spec §13) - derived from an already-existing
    immutable identifier (the CONTENT_GENERATION `EditorialTask.id`) via a stable CRC32 checksum,
    never a new DB sequence/migration and never used as a business/database key anywhere. Not
    guaranteed globally unique (a checksum of a UUID, not a counter) - purely a short, stable,
    human-scannable visual tag, exactly the spec's own "visual format only" scope."""
    checksum = zlib.crc32(str(identifier).encode("utf-8")) % 10_000
    return f"NP-{checksum:04d}"


def classify_presentation_category(
    title: str, content: str | None, research_facts: list[str] | None,
    fallback_category: EventCategory | None = None,
) -> str:
    """Article-level, deterministic, reuses services/channel_relevance.py's own already-tested
    `classify_article_topic()` (Phase 17 M2) rather than a new competing taxonomy. `fallback_
    category` (NewsEvent.category) only feeds that function's own `category_match` bookkeeping,
    which this module never reads - passing `EventCategory.UNKNOWN` when absent is exactly as
    correct as passing the real value for this module's own purposes (display category only,
    never NewsEvent.category directly - the spec's own explicit "not the single source of truth"
    instruction)."""
    assessment = classify_article_topic(
        title, content, research_facts or [], fallback_category or EventCategory.UNKNOWN,
    )
    return _TOPIC_TO_CATEGORY.get(assessment.primary_topic, CATEGORY_TECH)


def _ai_vetoes_breaking(copywriting_output: dict[str, Any] | None) -> bool:
    if not copywriting_output:
        return False
    viral = copywriting_output.get("viral_potential")
    return viral in ("NONE", "LOW")


def _breaking_guard_eligible(
    *, treatment: str, scoring_score: int | None, combined_text: str,
) -> tuple[bool, str]:
    """Deterministic BREAKING eligibility - reuses `services/editorial_treatment.py`'s own MAJOR
    tier (the strongest existing significance/evidence signal) as a hard prerequisite, never a
    second global-importance scoring system. A landmark-scale keyword AND a named major company
    must both be present - neither alone is sufficient (mirrors services/news_editorial_
    relevance.py's own major-impact-override discipline: no dollar figure or lone company mention
    is ever automatically "breaking")."""
    if treatment != MAJOR:
        return False, "treatment tier below MAJOR - BREAKING requires the strongest existing evidence gate"
    if scoring_score is None or scoring_score < _BREAKING_MIN_SCORE:
        return False, f"scoring_score below BREAKING floor ({_BREAKING_MIN_SCORE})"
    if _BREAKING_SIGNAL_PATTERN.search(combined_text) is None:
        return False, "no landmark-scale keyword evidence in title/content"
    if _BREAKING_COMPANY_PATTERN.search(combined_text) is None:
        return False, "no named major-company evidence in title/content"
    return True, "MAJOR treatment + strong score + landmark keyword + major-company match"


def _extract_number_unit_pairs(text: str) -> set[tuple[str, str]]:
    normalized = _normalize(text)
    pairs: set[tuple[str, str]] = set()
    for match in _NUMBER_UNIT_RE.finditer(normalized):
        value = match.group("value").replace(",", "").strip(".")
        unit = match.group("unit").rstrip(".").lower()
        pairs.add((value, unit))
    return pairs


def _find_data_candidate(
    title: str, main_body: str | None, research_facts: list[str] | None,
) -> DataCandidate | None:
    """Deterministic evidence binding (no Research fact IDs exist in this schema - see module
    docstring): a DATA candidate is accepted only when the SAME normalized (value, unit) pair
    appears BOTH in the copywriting text (what the AI proposed to highlight) AND in a Research
    fact (independent, already-verified evidence) - cross-verification, never trust in either
    source alone. No match in both places -> None -> caller falls back to NEWS."""
    if not research_facts:
        return None
    copy_text = f"{title} {main_body or ''}"
    copy_pairs = _extract_number_unit_pairs(copy_text)
    if not copy_pairs:
        return None

    for fact in research_facts:
        if not isinstance(fact, str):
            continue
        fact_pairs = _extract_number_unit_pairs(fact)
        common = copy_pairs & fact_pairs
        if not common:
            continue
        value, unit = sorted(common)[0]
        normalized_fact = _normalize(fact)
        match = _NUMBER_UNIT_RE.search(normalized_fact)
        label = fact.strip()
        if match:
            # A short surrounding label, taken verbatim from the fact text (never generated) -
            # the fact's own remainder after the matched number+unit span.
            label = " ".join((fact[: match.start()] + " " + fact[match.end():]).split())
            label = label or fact.strip()
        return DataCandidate(value=value, unit=unit, label=label[:80], evidence_fact=fact.strip())
    return None


def _find_quote_candidate(quote_text: str | None, quote_speaker: str | None) -> QuoteCandidate | None:
    """Reuses the exact already-verified/persisted quote this codebase already resolves via
    services/quote_lookup.py (worker/content_cycle.py resolves quote_text/quote_speaker before
    ever calling this module) - never a new extraction/verification mechanism. Attribution
    (a non-empty speaker) is required; a quote with no attributed speaker is never eligible."""
    if not quote_text or not quote_speaker:
        return None
    return QuoteCandidate(text=quote_text, speaker=quote_speaker)


def decide_presentation(
    *,
    title: str,
    content: str | None,
    copywriting_output: dict[str, Any] | None,
    treatment: str,
    scoring_score: int | None,
    research_facts: list[str] | None,
    quote_text: str | None,
    quote_speaker: str | None,
    fallback_category: EventCategory | None = None,
    breaking_count_this_cycle: int = 0,
    breaking_max_per_cycle: int = 1,
    breaking_enabled: bool = True,
) -> PresentationDecision:
    """Pure. Identical inputs always produce an identical decision. See module docstring for the
    AI-proposes/guard-validates split and the zero-new-LLM-call design.

    `breaking_enabled` (pre-commit correction, spec's own "BREAKING first-canary safety"): a
    narrow, deterministic kill switch for BREAKING specifically - wired from `settings.
    presentation_breaking_enabled` (default `True`, i.e. no behavior change) - so a first
    production canary can run `presentation_director_mode="enforce"` for NEWS/DATA/QUOTE while
    BREAKING (the single most visually aggressive template) is switched off separately, without
    touching `presentation_director_mode` itself (which would also silence NEWS/DATA/QUOTE) and
    without any new persistence/scheduler/scoring system - `False` simply skips the BREAKING guard
    entirely, falling through to the same DATA/QUOTE/NEWS evaluation every other story already
    gets."""
    category = classify_presentation_category(title, content, research_facts, fallback_category)
    main_body = copywriting_output.get("main_body") if copywriting_output else None
    combined_text = _normalize(f"{title} {content or ''} {main_body or ''}")

    if (
        breaking_enabled
        and breaking_count_this_cycle < breaking_max_per_cycle
        and not _ai_vetoes_breaking(copywriting_output)
    ):
        eligible, guard_reason = _breaking_guard_eligible(
            treatment=treatment, scoring_score=scoring_score, combined_text=combined_text,
        )
        if eligible:
            return PresentationDecision(
                presentation_type=BREAKING, category=category, caption_position=CAPTION_ABOVE,
                branding_strength=BRANDING_STRONG, brand_media=True, visual_priority=4,
                data_candidate=None, quote_candidate=None, reason=guard_reason,
            )

    data_candidate = _find_data_candidate(title, main_body, research_facts)
    if data_candidate is not None:
        return PresentationDecision(
            presentation_type=DATA, category=category, caption_position=CAPTION_BELOW,
            branding_strength=BRANDING_EDITORIAL, brand_media=True, visual_priority=3,
            data_candidate=data_candidate, quote_candidate=None,
            reason="numeric value cross-verified against a Research fact",
        )

    quote_candidate = _find_quote_candidate(quote_text, quote_speaker)
    if quote_candidate is not None:
        return PresentationDecision(
            presentation_type=QUOTE, category=category, caption_position=CAPTION_BELOW,
            branding_strength=BRANDING_EDITORIAL, brand_media=True, visual_priority=3,
            data_candidate=None, quote_candidate=quote_candidate,
            reason="verified, attributed quote already resolved via services/quote_lookup.py",
        )

    branding_strength, visual_priority = _BRANDING_BY_TREATMENT.get(treatment, (BRANDING_MINIMAL, 1))
    return PresentationDecision(
        presentation_type=NEWS, category=category, caption_position=CAPTION_BELOW,
        branding_strength=branding_strength, brand_media=True, visual_priority=visual_priority,
        data_candidate=None, quote_candidate=None, reason="default - no BREAKING/DATA/QUOTE evidence grounded",
    )
