"""Phase 16 M7 - shadow/live validation against real, already-collected NewsEvent rows (docs/
phase16_m7_shadow_validation_report.md). Mirrors scripts/phase16_m4_offline_backtest.py's own
established methodology (real events, direct `run_shadow_discovery()` calls, zero LLM/provider
calls) but additionally exercises the real M5 persistence write path (this milestone's own
purpose) and, for a bounded subset, real M5 "finalists" byte storage so a genuine visual/relevance
review is possible.

Three phases, run independently via the `--phase` flag:

  coverage  - Phase A: broad sample (SAMPLE_SIZE real recent events), mode="shadow",
              persistence_mode="metadata" (real DB writes, no bytes stored). Produces the
              quantitative pipeline-quality report (coverage, source mix, quality distribution,
              rejection reasons, dedup stats, ranking stats).
  finalists - Phase B: a bounded subset (FINALIST_SAMPLE_SIZE) of events from the coverage phase
              that produced >=1 ranked candidate, re-run with persistence_mode="finalists" so real
              bytes are stored under --storage-root (a scratchpad directory, never the production
              container path) for direct human/AI visual review.
  live-send - Phase C: links a SINGLE, already-real, already-completed CONTENT_GENERATION
              EditorialTask/ContentDraft's own image candidates (generated by re-running
              run_shadow_discovery for that same real event) and sends ONE real Telegram preview
              to settings.editorial_chat_id via services.image_preview_notifier.send_image_preview
              - zero new LLM calls (the ContentDraft already existed from the system's own past,
              unrelated real operation), zero synthetic events.

No phase creates a NewsEvent, EditorialTask, or ContentDraft - only image_candidates rows (the
exact table this milestone's validation goal is to exercise for real). No phase calls OpenAI or
any LLM/vision provider (`run_shadow_discovery()` itself makes zero such calls, confirmed by every
M1-M6 report's own AST-based import-boundary test).

Launch with:
    python -m scripts.phase16_m7_shadow_validation --phase coverage
    python -m scripts.phase16_m7_shadow_validation --phase coverage --event-ids-file ids.json
    python -m scripts.phase16_m7_shadow_validation --phase finalists --storage-root ./scratchpad/m7_images
    python -m scripts.phase16_m7_shadow_validation --phase live-send --event-id <uuid> --storage-root ./scratchpad/m7_images

Phase 16.5 (docs/phase16_5_image_calibration_report.md): the `coverage` phase now also reports
`generic_aggregator_top_choice_count`/`rate` directly (the exact KPI M7 measured at 29%) and always
prints its own `sampled_event_ids` so a later run can pin `--event-ids-file` to the identical real
sample for a true before/after comparison - no need to re-derive "the same 100 events" from
collection timestamps, which drift as the real system keeps collecting.
"""
import argparse
import asyncio
import json
from collections import Counter
from collections.abc import Sequence
from urllib.parse import urlsplit
from uuid import UUID

from sqlalchemy import Row, select
from sqlalchemy.ext.asyncio import AsyncSession

from core.config import settings
from database.models.content_draft import ContentDraft
from database.models.editorial_task import EditorialTask
from database.models.news_event import NewsEvent
from database.models.news_source import NewsSource
from database.session import async_session_factory
from services.image_intelligence import run_shadow_discovery
from services.image_persistence import link_candidates_to_content_draft

SAMPLE_SIZE = 100
FINALIST_SAMPLE_SIZE = 30


def _registrable_domain(url: str | None) -> str | None:
    if not url:
        return None
    try:
        host = urlsplit(url).hostname
    except ValueError:
        return None
    if not host:
        return None
    labels = host.lower().split(".")
    return ".".join(labels[-2:]) if len(labels) >= 2 else host


def _is_generic_google_asset(remote_url: str | None) -> bool:
    """Mirrors services.image_relevance's own generic-asset domain set - kept as an independent,
    duplicated check here (not imported) so this validation script measures the observable KPI
    (does the chosen top image resolve to one of Google's own asset domains) rather than merely
    asserting the production code agrees with itself."""
    return _registrable_domain(remote_url) in {"google.com", "googleusercontent.com", "gstatic.com"}


async def _sample_recent_events(
    session: AsyncSession, limit: int, event_ids: list[str] | None = None,
) -> Sequence[Row]:
    if event_ids:
        stmt = (
            select(NewsEvent, NewsSource.type, NewsSource.name)
            .join(NewsSource, NewsSource.id == NewsEvent.source_id)
            .where(NewsEvent.id.in_([UUID(e) for e in event_ids]))
        )
        rows = (await session.execute(stmt)).all()
        by_id = {str(row[0].id): row for row in rows}
        return [by_id[e] for e in event_ids if e in by_id]

    stmt = (
        select(NewsEvent, NewsSource.type, NewsSource.name)
        .join(NewsSource, NewsSource.id == NewsEvent.source_id)
        .order_by(NewsEvent.collected_at.desc())
        .limit(limit)
    )
    return (await session.execute(stmt)).all()


def _quality_bucket(score: int) -> str:
    if score >= 90:
        return "90-100"
    if score >= 70:
        return "70-90"
    if score >= 50:
        return "50-70"
    return "below_50"


async def run_coverage_phase(event_ids: list[str] | None = None) -> dict:
    async with async_session_factory() as session:
        settings.image_candidate_persistence_mode = "metadata"
        rows = await _sample_recent_events(session, SAMPLE_SIZE, event_ids=event_ids)

        events_with_candidates = 0
        events_with_zero_candidates_after_fix = 0
        source_type_counts: Counter = Counter()
        source_type_with_image_counts: Counter = Counter()
        discovery_method_counts: Counter = Counter()
        quality_status_counts: Counter = Counter()
        quality_score_buckets: Counter = Counter()
        hard_rejection_reason_counts: Counter = Counter()
        quality_warning_counts: Counter = Counter()
        exact_duplicate_clusters = 0
        near_duplicate_clusters = 0
        representative_count = 0
        relevance_status_counts: Counter = Counter()
        relevance_scores: list[int] = []
        ranked_events = 0
        top_candidate_details = []
        generic_aggregator_top_choice_events = 0
        generic_aggregator_excluded_candidates = 0
        sampled_event_ids: list[str] = []

        for event, source_type, source_name in rows:
            sampled_event_ids.append(str(event.id))
            result = await run_shadow_discovery(
                event_id=event.id, source_type=source_type, content=event.content,
                article_url=event.url, mode="shadow", event_title=event.title, source_name=source_name,
                session=session, editorial_task_id=None,
            )
            source_type_counts[source_type.value] += 1
            if result.candidates:
                events_with_candidates += 1
                source_type_with_image_counts[source_type.value] += 1
            if result.candidates_ranked > 0:
                ranked_events += 1

            event_has_generic_top_choice = False
            for candidate in result.candidates:
                discovery_method_counts[candidate.discovery_method.value] += 1
                quality = candidate.quality_validation
                if quality is not None:
                    quality_status_counts[quality.status.value] += 1
                    quality_score_buckets[_quality_bucket(quality.quality_score)] += 1
                    for reason in quality.hard_rejection_reasons:
                        hard_rejection_reason_counts[reason] += 1
                    for warning in quality.quality_warnings:
                        quality_warning_counts[warning] += 1
                    dedup = quality.deduplication
                    if dedup.exact_cluster_id and dedup.is_representative:
                        exact_duplicate_clusters += 1
                    if dedup.perceptual_cluster_id and dedup.is_representative and dedup.hamming_distance is not None:
                        near_duplicate_clusters += 1
                    if dedup.is_representative:
                        representative_count += 1
                relevance = candidate.relevance_validation
                if relevance is not None:
                    relevance_status_counts[relevance.status.value] += 1
                    if relevance.status.value == "ranked":
                        relevance_scores.append(relevance.relevance_score)
                    if relevance.eligibility_reason == "generic_aggregator_asset":
                        generic_aggregator_excluded_candidates += 1
                    if relevance.eligible_for_editorial:
                        if _is_generic_google_asset(candidate.remote_url):
                            event_has_generic_top_choice = True
                        top_candidate_details.append({
                            "event_id": str(event.id), "title": event.title[:100],
                            "source_type": source_type.value, "candidate_id": candidate.candidate_id,
                            "discovery_method": candidate.discovery_method.value,
                            "quality_score": quality.quality_score if quality else None,
                            "relevance_score": relevance.relevance_score,
                            "source_relationship": relevance.source_relationship.value if relevance.source_relationship else None,
                            "reason": relevance.reason,
                        })
            if event_has_generic_top_choice:
                generic_aggregator_top_choice_events += 1
            if not result.top_candidate_ids:
                events_with_zero_candidates_after_fix += 1

        await session.commit()

        summary = {
            "events_sampled": len(rows),
            "sampled_event_ids": sampled_event_ids,
            "events_with_image_candidates": events_with_candidates,
            "events_without_image_candidates": len(rows) - events_with_candidates,
            "events_with_ranked_candidate": ranked_events,
            "events_with_zero_eligible_top_candidate": events_with_zero_candidates_after_fix,
            "generic_aggregator_top_choice_events": generic_aggregator_top_choice_events,
            "generic_aggregator_top_choice_rate": (
                round(generic_aggregator_top_choice_events / len(rows), 4) if rows else None
            ),
            "generic_aggregator_excluded_candidates": generic_aggregator_excluded_candidates,
            "source_type_distribution": dict(source_type_counts),
            "source_type_with_image_distribution": dict(source_type_with_image_counts),
            "discovery_method_distribution": dict(discovery_method_counts),
            "quality_status_distribution": dict(quality_status_counts),
            "quality_score_buckets": dict(quality_score_buckets),
            "hard_rejection_reason_counts": dict(hard_rejection_reason_counts),
            "quality_warning_counts": dict(quality_warning_counts),
            "exact_duplicate_representative_clusters": exact_duplicate_clusters,
            "near_duplicate_representative_clusters": near_duplicate_clusters,
            "representative_candidate_count": representative_count,
            "relevance_status_distribution": dict(relevance_status_counts),
            "relevance_score_distribution": {
                "min": min(relevance_scores) if relevance_scores else None,
                "max": max(relevance_scores) if relevance_scores else None,
                "avg": round(sum(relevance_scores) / len(relevance_scores), 1) if relevance_scores else None,
                "count": len(relevance_scores),
            },
            "top_candidates_for_manual_review": top_candidate_details,
        }
        return summary


async def run_finalists_phase(storage_root: str, event_ids: list[str]) -> dict:
    settings.image_storage_root = storage_root
    settings.image_candidate_persistence_mode = "finalists"
    settings.image_max_stored_per_event = 1  # only the top-ranked candidate per event needed for review

    stored = []
    async with async_session_factory() as session:
        for event_id_str in event_ids[:FINALIST_SAMPLE_SIZE]:
            event = await session.get(NewsEvent, UUID(event_id_str))
            if event is None:
                continue
            source = await session.get(NewsSource, event.source_id)
            if source is None:
                continue
            result = await run_shadow_discovery(
                event_id=event.id, source_type=source.type, content=event.content,
                article_url=event.url, mode="shadow", event_title=event.title, source_name=source.name,
                session=session, editorial_task_id=None,
            )
            await session.commit()
            if result.top_candidate_ids:
                stored.append({"event_id": str(event.id), "title": event.title, "url": event.url})

    return {"storage_root": storage_root, "events_processed": min(len(event_ids), FINALIST_SAMPLE_SIZE), "events_with_stored_finalist": len(stored), "events": stored}


async def run_live_send_phase(storage_root: str, event_id: str) -> dict:
    from aiogram.exceptions import TelegramAPIError

    from bot.loader import create_bot
    from services.image_preview_notifier import send_image_preview

    settings.image_storage_root = storage_root
    settings.image_candidate_persistence_mode = "finalists"

    async with async_session_factory() as session:
        event = await session.get(NewsEvent, UUID(event_id))
        if event is None:
            return {"status": "event_not_found", "event_id": event_id}
        source = await session.get(NewsSource, event.source_id)
        if source is None:
            return {"status": "source_not_found", "event_id": event_id}

        task_stmt = select(EditorialTask).where(
            EditorialTask.event_id == event.id,
            EditorialTask.workflow["workflow_name"].as_string() == "CONTENT_GENERATION",
        )
        task = (await session.execute(task_stmt)).scalars().first()
        if task is None:
            return {"status": "no_content_generation_task", "event_id": event_id}
        draft = (await session.execute(select(ContentDraft).where(ContentDraft.task_id == task.id))).scalars().first()
        if draft is None:
            return {"status": "no_content_draft", "event_id": event_id}

        result = await run_shadow_discovery(
            event_id=event.id, source_type=source.type, content=event.content,
            article_url=event.url, mode="shadow", event_title=event.title, source_name=source.name,
            session=session, editorial_task_id=task.id,
        )
        await session.commit()

        linked = await link_candidates_to_content_draft(session, editorial_task_id=task.id, content_draft_id=draft.id)
        await session.commit()

        bot = create_bot()
        try:
            outcome = await send_image_preview(
                bot, settings.editorial_chat_id, session, content_draft_id=draft.id, draft_title=draft.title,
            )
        except TelegramAPIError as error:
            return {"status": "telegram_api_error", "error": str(error)}
        finally:
            await bot.session.close()

        return {
            "status": "sent" if outcome.sent else ("no_candidates" if not outcome.attempted else "send_failed"),
            "event_id": event_id, "task_id": str(task.id), "draft_id": str(draft.id),
            "candidates_linked": linked, "candidate_count": outcome.candidate_count,
            "chat_id": settings.editorial_chat_id, "top_candidate_ids": result.top_candidate_ids,
        }


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase", choices=["coverage", "finalists", "live-send"], required=True)
    parser.add_argument("--storage-root", default="./scratchpad/m7_images")
    parser.add_argument("--event-ids-file", default=None, help="JSON file with a list of event_id strings (coverage/finalists phases)")
    parser.add_argument("--event-id", default=None, help="single event_id (live-send phase)")
    args = parser.parse_args()

    if args.phase == "coverage":
        pinned_ids = None
        if args.event_ids_file:
            with open(args.event_ids_file, encoding="utf-8") as handle:
                pinned_ids = json.load(handle)
        summary = await run_coverage_phase(pinned_ids)
    elif args.phase == "finalists":
        with open(args.event_ids_file, encoding="utf-8") as handle:
            event_ids = json.load(handle)
        summary = await run_finalists_phase(args.storage_root, event_ids)
    else:
        assert args.event_id is not None, "--event-id is required for --phase live-send"
        summary = await run_live_send_phase(args.storage_root, args.event_id)

    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    asyncio.run(main())
